name: C/C++ CI

on:
  push:
    branches: [ master, task4 ]
  pull_request:
    branches: [ master, task4 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'Build'
      run: |
        echo ${pwd}
        git clone https://github.com/google/googletest 3rdparty
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=$(pwd)/.. ..
        make
        make install
    - name: 'Test'
      run: echo "k"
    - name: 'UploadArtifacts'
      run: echo "k"
